name: Validations

on:
  pull_request:
    branches: [master, main, develop]

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  verifications:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Cambiar al directorio donde se encuentra el archivo .pre-commit-config.yaml
      - name: Change to project directory
        run: cd TP4   # Reemplaza "TP4" con el nombre de tu carpeta si es diferente

      # Verificar si el archivo .pre-commit-config.yaml está presente
      - name: Check for .pre-commit-config.yaml
        run: ls -l

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"
      - name: Install Ceedling
        run: gem install ceedling
      - name: Install GCov Reporter
        run: pip install gcovr
      - name: Run Format Validations
        uses: pre-commit/action@v3.0.0
      - name: Run Unit Tests
        run: ceedling clobber gcov:all utils:gcov
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Ceedling Unit Tests
          path: TP4/build/artifacts/gcov/report.xml  # Ruta ajustada para el reporte de pruebas
          reporter: jest-junit
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: TP4/build/artifacts/gcov/GcovCoverageCobertura.xml  # Ruta ajustada para el reporte de cobertura
          badge: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: "60 80"
      - name: Output to Job Summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
