name: Validaciones

on:
  pull_request:
    branches: [master, main, develop]

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  verifications:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: List files
        run: ls

      - name: List files TP4
        run: ls -a TP4

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"

      - name: Install Ceedling
        run: gem install ceedling

      - name: Install GCov Reporter
        run: pip install gcovr

      # Run Pre-Commit Checks only in TP4 directory
      - name: Run Pre-Commit Checks
        uses: pre-commit/action@v3.0.0
        with:
          path: .pre-commit-config.yaml
          args: ['--files', 'TP4']

      # Rest of the workflow steps remain the same
      - name: Run Unit Tests
        run: ceedling clobber gcov:all utils:gcov

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Ceedling Unit Tests
          path: build/artifacts/gcov/report.xml
          reporter: jest-junit

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: build/artifacts/gcov/GcovCoverageCobertura.xml
          badge: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: "60 80"

      - name: Output to Job Summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
