name: Validations

on:
  pull_request:
    branches: [master, main, development]

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  verifications:
    runs-on: ubuntu-latest
    steps:
      - name: Print current directory
        run: pwd
      - name: pasar a directorio aterior
        run: cd..
      - name: lista de directorios
        run: ls -a
      - name: Change Directory to TP4
        run: cd TSSE/TP4
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"
      - name: Install pre-commit
        run: python -m pip install pre-commit
      - name: Install Ceedling
        run: gem install ceedling
      - name: Install GCov Reporter
        run: pip install gcovr
      - name: Run pre-commit
        run: pre-commit run --all-files
      - name: Run Unit Tests
        run: ceedling clobber gcov:all utils:gcov
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Ceedling Unit Tests
          path: build/artifacts/gcov/report.xml
          reporter: jest-junit
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: build/artifacts/gcov/GcovCoverageCobertura.xml
          badge: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: "60 80"
      - name: Output to Job Summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
