name: Validaciones

on:
  pull_request:
    branches: [master, main, develop]

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  verifications:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: lista de directorios
        run: ls

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"

      - name: Install Ceedling
        run: gem install ceedling
        working-directory: TP4

      - name: Install GCov Reporter
        run: pip install gcovr
        working-directory: TP4

      - name: List files in TP4 directory TSSE
        run: ls TSSE

      - name: List files in TP4 directory
        run: ls TP4

      - name: Run Format Validations
        uses: pre-commit/action@v3.0.0
        with:
          path: TP4

      - name: Run Unit Tests
        run: ceedling clobber gcov:all utils:gcov
        working-directory: TP4

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Ceedling Unit Tests
          path: TP4/build/artifacts/gcov/report.xml
          reporter: jest-junit

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: TP4/build/artifacts/gcov/GcovCoverageCobertura.xml
          badge: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: "60 80"

      - name: Output to Job Summary
        run: cat TP4/code-coverage-results.md >> $GITHUB_STEP_SUMMARY

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: TP4/code-coverage-results.md
